// Objective-C API for talking to github.com/ribencong/go-lib/ios Go package.
//   gobind -lang=objc github.com/ribencong/go-lib/ios
//
// File is generated by gobind. Do not edit.

#ifndef __IosLib_H__
#define __IosLib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull const IosLibDefaultDomainUrl;
FOUNDATION_EXPORT NSString* _Nonnull const IosLibSeparator;

FOUNDATION_EXPORT NSString* _Nonnull IosLibCreateAccount(NSString* _Nullable password);

FOUNDATION_EXPORT NSString* _Nonnull IosLibFindBestNode(NSString* _Nullable nodesStr);

FOUNDATION_EXPORT NSData* _Nullable IosLibGenAesKey(NSData* _Nullable priKey, NSString* _Nullable peerID);

FOUNDATION_EXPORT NSData* _Nullable IosLibGenPriKey(NSString* _Nullable cipherTxt, NSString* _Nullable address, NSString* _Nullable password);

FOUNDATION_EXPORT NSString* _Nonnull IosLibLoadDomain(NSString* _Nullable url);

FOUNDATION_EXPORT NSString* _Nonnull IosLibLoadNodes(void);

FOUNDATION_EXPORT BOOL IosLibVerifyAccount(NSString* _Nullable cipherTxt, NSString* _Nullable address, NSString* _Nullable password);

FOUNDATION_EXPORT BOOL IosLibVerifyLicense(NSString* _Nullable license);

#endif
