
// Objective-C API for talking to the following Go packages
//
//	github.com/ribencong/go-lib/ios
//
// File is generated by gomobile bind. Do not edit.
#ifndef __IosLib_FRAMEWORK_H__
#define __IosLib_FRAMEWORK_H__

#include "IosLib.objc.h"
#include "Universe.objc.h"

#endif
