// Objective-C API for talking to github.com/ribencong/go-lib/ios Go package.
//   gobind -lang=objc github.com/ribencong/go-lib/ios
//
// File is generated by gobind. Do not edit.

#ifndef __IosLib_H__
#define __IosLib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol IosLibVpnDelegate;
@class IosLibVpnDelegate;

@protocol IosLibVpnDelegate <NSObject>
- (BOOL)byPass:(int32_t)fd;
- (void)log:(NSString* _Nullable)str;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT BOOL IosLibInitVPN(id<IosLibVpnDelegate> _Nullable d, NSString* _Nullable lAddr, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void IosLibInputPacketData(NSData* _Nullable data);

@class IosLibVpnDelegate;

@interface IosLibVpnDelegate : NSObject <goSeqRefInterface, IosLibVpnDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)byPass:(int32_t)fd;
- (void)log:(NSString* _Nullable)str;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

#endif
