// Objective-C API for talking to github.com/ribencong/go-lib/ios Go package.
//   gobind -lang=objc github.com/ribencong/go-lib/ios
//
// File is generated by gobind. Do not edit.

#ifndef __IosLib_H__
#define __IosLib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol IosLibVPNOutLogger;
@class IosLibVPNOutLogger;

@protocol IosLibVPNOutLogger <NSObject>
- (void)log:(NSString* _Nullable)str;
@end

FOUNDATION_EXPORT void IosLibDumpPacket(NSData* _Nullable data);

FOUNDATION_EXPORT void IosLibHttpServer(NSString* _Nullable lAddr);

FOUNDATION_EXPORT void IosLibInitVPN(id<IosLibVPNOutLogger> _Nullable l);

@class IosLibVPNOutLogger;

@interface IosLibVPNOutLogger : NSObject <goSeqRefInterface, IosLibVPNOutLogger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)log:(NSString* _Nullable)str;
@end

#endif
