// Objective-C API for talking to github.com/ribencong/go-lib/ios Go package.
//   gobind -lang=objc github.com/ribencong/go-lib/ios
//
// File is generated by gobind. Do not edit.

#ifndef __IosDelegate_H__
#define __IosDelegate_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull IosDelegateParseNsData(NSData* _Nullable data);

#endif
